php:
  preset: laravel
  version: 8.2
  finder:
    not-name:
      - bad-syntax-strategy.php
js:
  finder:
    not-name:
      - src/Illuminate/Foundation/resources/exceptions/renderer/dist
      - webpack.mix.js
css:
  finder:
    not-name:
      - src/Illuminate/Foundation/resources/exceptions/renderer/dist
